# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='My location', max_length=1200),
        ),
    ]
