# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
